# Generated by Django 5.2 on 2025-05-07 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='exam_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='option1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='option2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='option3',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='option4',
            field=models.CharField(max_length=1000),
        ),
    ]
