# Generated by Django 5.2 on 2025-05-07 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_mcqquestion_exam_name_alter_mcqquestion_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='batch',
            field=models.CharField(default='cp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='option3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='option4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
