# Generated by Django 5.2 on 2025-05-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_mcqquestion_batch_mcqquestion_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
