# Generated by Django 5.2 on 2025-05-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
