# Generated by Django 5.2 on 2025-05-26 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='test_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.test'),
        ),
    ]
