# Generated by Django 5.2 on 2025-05-26 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_mcqquestion_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.batch'),
        ),
    ]
