# Generated by Django 5.2 on 2025-05-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_mcqquestion_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='exam_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course'),
        ),
    ]
