# Generated by Django 5.2 on 2025-05-27 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_mcqquestion_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamrecord',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='test_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.test'),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.test'),
        ),
    ]
