# Generated by Django 5.2 on 2025-05-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_studentexamrecord_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamrecord',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
