# Generated by Django 5.2 on 2025-05-27 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_studentexamrecord_marks'),
        ('user_auth', '0002_alter_profile_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exam.batch'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exam.course'),
        ),
    ]
